name: Mi flujo de trabajo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Ejecutar un comando
        run: echo "Hola, mundo!"
